### ISSUE TITLE
创建钱包接口问题

### ISSUE THREAD

**Issue by LyyDandelion** [xuehongyang/FilecoinJ#1]
filecoin.createWallet()这个接口没有调用api，生成的地址要通过import调用导入进去吗？如果你生成的钱包地址在链上存在了这样会有问题吧

**Comment by xuehongyang** [comment]
这种生成方式属于离线加密，不是必须导入节点的，地址和对应私钥保存到数据库也是可以的。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuehongyang/FilecoinJ"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月28日(星期四) 晚上6:13
收件人:&nbsp;"xuehongyang/FilecoinJ"<FilecoinJ@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xuehongyang/FilecoinJ] 创建钱包接口问题 (#1)





 
filecoin.createWallet()这个接口没有调用api，生成的地址要通过import调用导入进去吗？如果你生成的钱包地址在链上存在了这样会有问题吧

**Comment by LyyDandelion** [comment]
好的，谢谢
