### ISSUE TITLE
怎么通过消息的Cid获取收据？

### ISSUE THREAD

**Issue by qq335103060** [xuehongyang/FilecoinJ#11]
在做归集的时候如何通过转账的Cid来判断是否交易成功

**Comment by xuehongyang** [comment]
项目里已经有获取收据的api了，具体使用要根据你的业务去做数据处理。获取当前交易所在区块的子块cid，然后根据这个cid就能获取到当前交易所在区块的所有收据，找出你的交易收据判断就行了。

**Comment by qq335103060** [comment]
> 项目里已经有获取收据的api了，具体使用要根据你的业务去做数据处理。获取当前交易所在区块的子块cid，然后根据这个cid就能获取到当前交易所在区块的所有收据，找出你的交易收据判断就行了。

通过ChainGetMessage无法查询到这个交易消息的子块cid，返回报文里面这样交易消息自己的Cid

**Comment by xuehongyang** [comment]
你可以通过区块编号查，你的交易所在区块编号为100，那你就查101的区块

**Comment by qq335103060** [comment]
> 你可以通过区块编号查，你的交易所在区块编号为100，那你就查101的区块

好像是没有API查询消息Cid所在区块高度

**Comment by xuehongyang** [comment]
换个思路的话可以解决，监听归集接收地址，就像做充值那样去扫描，需要的数据就都有了。

**Comment by qq335103060** [comment]
> 换个思路的话可以解决，监听归集接收地址，就像做充值那样去扫描，需要的数据就都有了。

我想的最坏的打算就只能是在扫用户充值入账地址的时候一起扫归集接收地址了

**Comment by xuehongyang** [comment]
Filecoin.StateGetReceipt
这个api也是获取交易收据，看看能不能满足你。按道理归集是自己发起的可信任交易不用那么严谨。

**Comment by qq335103060** [comment]
> Filecoin.StateGetReceipt
> 这个api也是获取交易收据，看看能不能满足你。按道理归集是自己发起的可信任交易不用那么严谨。

好的，谢谢
