### ISSUE TITLE
充值入账API咨询，谢谢。

### ISSUE THREAD

**Issue by knight2008** [xuehongyang/FilecoinJ#12]
13.获取指定高度的所有消息(非充值入账业务标准API！！！)
14.获取消息收据(非充值入账业务标准API！！！)
大佬，请教一下，这2个为什么不能作为充值入账？
扫描到指定高度的所有消息，然后按顺序获取所有交易的收据，这个有什么问题呢？

**Comment by xuehongyang** [comment]
会被充值攻击，两笔nonce相同的交易，肯定一个成功一个失败。
但是如果使用这两个api就是两个都成功。

**Comment by knight2008** [comment]
大概明白了，这个对接起来麻烦一些，多谢了，infura转账还经常卡。。。
