### ISSUE TITLE
如何修改矿工费后重新上链

### ISSUE THREAD

**Issue by XoXOoOToT** [xuehongyang/FilecoinJ#4]
大佬，测试的交易的时候发现gas费设置过低导致没有上链，请问有哪个api可以修改矿工费并重新发送交易

**Comment by xuehongyang** [comment]
重新发一笔交易，nonce和要覆盖的交易一致即可。发自我的华为手机-------- 原始邮件 --------发件人： kxkxkxkxkx ***@***.***>日期： 2021年3月24日周三 20:19收件人： xuehongyang/FilecoinJ ***@***.***>抄送： Subscribed ***@***.***>主    题： [xuehongyang/FilecoinJ] 如何修改矿工费后重新上链 (#4)

大佬，测试的交易的时候发现gas费设置过低导致没有上链，请问有哪个api可以修改矿工费并重新发送交易

**Comment by XoXOoOToT** [comment]
可以了，感谢🙏。把接口返回的gas都调高瞬间成功

**Comment by xuehongyang** [comment]
跟你说一个我踩的坑，根据from to num去链上估算gas的时候，如果to是一个新地址，那么返回的gasCap是远远低于正常gasCap的，这一点你可以验证下。不保证主网现在还有这个特性，这是我之前遇到的。-------- 原始邮件 --------发件人： kxkxkxkxkx ***@***.***>日期： 2021年3月24日周三 23:06收件人： xuehongyang/FilecoinJ ***@***.***>抄送： xuehongyang ***@***.***>, Comment ***@***.***>主    题： Re: [xuehongyang/FilecoinJ] 如何修改矿工费后重新上链 (#4)

可以了，感谢🙏。把接口返回的gas都调高瞬间成功

**Comment by XoXOoOToT** [comment]
对对对，我也是这个情况，我想通过交易激活一个离线地址，发现gascap太低导致创建失败。心累。大概激活一个地址我是用了0.05FIL

**Comment by xuehongyang** [comment]
我没有刻意去做激活操作，我在业务里维护一个gasCapMin值,根据主网情况动态调整。每次getGas都会做判断：gasCap = （gasCap > gasCapMin ? gasCap ? gasCapMin）;

**Comment by xuehongyang** [comment]
我没有刻意去做激活操作，我在业务里维护一个gasCapMin值,根据主网情况动态调整。每次getGas都会做判断：gasCap = （gasCap > gasCapMin ? gasCap ? gasCapMin）;
