### ISSUE TITLE
离线钱包生成的地址是否会重复

### ISSUE THREAD

**Issue by XoXOoOToT** [xuehongyang/FilecoinJ#5]
大神，请教一下，离线生成的地址是否会和主网上的地址冲突，因为没有搭建节点，怕出现这种情况

**Comment by xuehongyang** [comment]
我们创建的地址，都是由随机数获得私钥加密获得的，所有可能出现的私钥足够给宇宙的每一个原子分配一个，理论上不会重复，这个问题不用考虑。
