### ISSUE TITLE
你好，我打包filecoinj后进行进入，出现了classnotfound 问题

### ISSUE THREAD

**Issue by paipaipaipai** [xuehongyang/FilecoinJ#6]
![image](https://user-images.githubusercontent.com/30950645/113982436-55a1d280-987b-11eb-9aa4-1a10f926182c.png)

**Comment by paipaipaipai** [comment]
![image](https://user-images.githubusercontent.com/30950645/113983522-93532b00-987c-11eb-8e6e-01b590120585.png)

**Comment by xuehongyang** [comment]
检查下你的maven是不是有些依赖没导入成功，或者在代码里尝试导入找不到的类，验证是否真的不存在。

**Comment by paipaipaipai** [comment]
![Uploading image.png…]()

**Comment by paipaipaipai** [comment]
导入后我的包找这样，但是当我跑程序的时候，才出现错误

**Comment by paipaipaipai** [comment]
编译的时候没有出现错误

**Comment by paipaipaipai** [comment]
![image](https://user-images.githubusercontent.com/30950645/113986575-f85c5000-987f-11eb-9d1d-1cef8d68e559.png)

**Comment by paipaipaipai** [comment]
我在依赖中找到了他

**Comment by xuehongyang** [comment]
你是直接运行filecoinJ内的函数，还是在其他项目中引用了filecoinJ来执行的。

**Comment by paipaipaipai** [comment]
在其他项目中引用了filecoinJ来执行的。

**Comment by xuehongyang** [comment]
可能是依赖冲突，大多数区块链项目的依赖都有重合

**Comment by paipaipaipai** [comment]
那怎么解决呢

**Comment by xuehongyang** [comment]
如果是依赖冲突，找到冲突的依赖，去掉

**Comment by paipaipaipai** [comment]
暂时没有发现是依赖冲突的问题

**Comment by paipaipaipai** [comment]
我加入了这个解决这个问题
`        
        <dependency>
            <groupId>com.madgag.spongycastle</groupId>
            <artifactId>core</artifactId>
            <version>1.58.0.0</version>
        </dependency>`
