### ISSUE TITLE
关于easy transfer的参数问题，gasfeecap 和gaslimit调优

### ISSUE THREAD

**Issue by paipaipaipai** [xuehongyang/FilecoinJ#8]
关于easy transfer的参数问题，gasfeecap 和gaslimit调优，这个现在我是通过getgas方法后 获取里面的值各乘以2倍，但是发现实际用不到这么多

**Comment by paipaipaipai** [comment]
我想问一下，为什么要设置gaslimit*2 gascap*2

**Comment by xuehongyang** [comment]
https://github.com/xuehongyang/FilecoinJ/issues/4#issuecomment-806324824

我没有使用easy transfer方法，我使用的是普通transfer。这是我遇到的gasCap问题的解决办法，在这个issues有回答
